### ISSUE TITLE
TypeError: 'JSObject' object is not iterable

### ISSUE THREAD

**Issue by lixiaozhui** [imgcook/boa#21]
`
 def reset(self,card_play_data):
      
        self._env.reset()

        # card_play_data = {'landlord': _deck[:20],
        #                   'landlord_up': _deck[20:37],
        #                   'landlord_down': _deck[37:54],
        #                   'three_landlord_cards': _deck[17:20],
        #                   }
        for key in card_play_data:
            card_play_data[key].sort()
        # Initialize the cards
        self._env.card_play_init(card_play_data)
        self.infoset = self._game_infoset

        # return get_obs(self.infoset)
`

The above is a python function. The passed parameter ‘card_play_data’ is a dict. However, when calling this function from node, a type {}
 like

`
let cardPlayData = {
                landlord: _deck.slice(0, 20),
                landlord_up: _deck.slice(20, 37),
                landlord_down: _deck.slice(37, 54),
                three_landlord_cards: _deck.slice(17,20)
            };
`

 is passed to python and it is recognized as JSObject, which does not support the built-in dict feature.

**Comment by yorkie** [comment]
@lixiaozhui May I ask you to make a better format for your code block?

As for your question, to make sure you pass a dict to your python function, you could create a dict in JavaScript by `boa.builtins().dict` by yourself.

And the cast from JavaScript object to dict, Boa has an implementation here: https://github.com/imgcook/boa/blob/main/src/core/object.cc#L513-L539.

**Comment by yorkie** [comment]
> @lixiaozhui May I ask you to make a better format for your code block?
> 
> As for your question, to make sure you pass a dict to your python function, you could create a dict in JavaScript by `boa.builtins().dict` by yourself.
> 
> And the cast from JavaScript object to dict, Boa has an implementation here: https://github.com/imgcook/boa/blob/main/src/core/object.cc#L513-L539.

In this implementation, it creates a new type with `JSObject` and instantiate from the JavaScript object's properties.

```c++
pybind::object type =
      pybind::reinterpret_borrow<pybind::object>((PyObject *)&PyType_Type);
pybind::dict attrs = pybind::reinterpret_borrow<pybind::dict>(dict);
// FIXME(yorkie): use "JSObject" as the default object name to Python.
return type("JSObject", pybind::make_tuple(), attrs)().release().ptr();
```

**Comment by lixiaozhui** [comment]
> > @lixiaozhui May I ask you to make a better format for your code block?
> > As for your question, to make sure you pass a dict to your python function, you could create a dict in JavaScript by `boa.builtins().dict` by yourself.
> > And the cast from JavaScript object to dict, Boa has an implementation here: https://github.com/imgcook/boa/blob/main/src/core/object.cc#L513-L539.
> 
> In this implementation, it creates a new type with `JSObject` and instantiate from the JavaScript object's properties.
> 
> ```c++
> pybind::object type =
>       pybind::reinterpret_borrow<pybind::object>((PyObject *)&PyType_Type);
> pybind::dict attrs = pybind::reinterpret_borrow<pybind::dict>(dict);
> // FIXME(yorkie): use "JSObject" as the default object name to Python.
> return type("JSObject", pybind::make_tuple(), attrs)().release().ptr();
> ```

It worked as you said，When I modified cardPlayData as shown below
>```python
>const cardPlayData  = boa.builtins().dict(boa.kwargs({landlord: [3,3,3,3,6,7,8], landlord_up: [4,4,4,4], landlord_down: [5,5,5,5,], >three_landlord_cards: [6,7,8]}));
>```

thank you very much!!!
